// <auto-generated />
namespace BJ2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Addnewfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addnewfields));
        
        string IMigrationMetadata.Id
        {
            get { return "202411232156226_Add new fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
